# Set the global path of project
# Memo: If use the Vagrant based singularity, this might be '/vagrant'
project_root: '/home/projects/rth/co2capture/subprojects/OCyRS/OCyRS-pipeline'

# Specify which phylum to search in
phylum: 'Cyanobacteria'


