# Set the global path of project
# Memo: If use the Vagrant based singularity, this might be '/vagrant'
project_root: '/home/projects/rth/co2capture/subprojects/OCyRS/OCyRS-pipeline'

# Specify which phylum to search in
phylum: 'Cyanobacteria'

# Specify Rfam version
rfamv: '14.8'

# After CMfinder runs and FDR estimation, continue with
# candidates for cmsearch etc with this cutoff
fdr_candidates: 10

