__default__:
    time: 0-01:00:00
    job-name: '{rule}'
    cpus: 1
    mem: 8GB
    partition: bullseye
    output: 'slurmlogs/{rule}_$(date "+%Y-%m-%d_%H-%M-%S")_job%j.out.txt'
    error: 'slurmlogs/{rule}_$(date "+%Y-%m-%d_%H-%M-%S")_job%j.err.txt'

A_checkm:
    cpus: 8
    mem: 40GB

B_seqids:
    cpus: 8

C_phylo:
    cpus: 16 
    mem: 20GB
    time: 0-10:00:00
